[meta]
name = "Speedrun map switcher"
author = "Glocom"
category = "Speedrunning"

blocks = [ "Speedrunning_Test" ]

siteid = 87
version = "1.8.0"

perms = "paid"

[game]
min_version = "2021-10-01"

[script]
imports = [ "Icons.as", "Formatting.as", "Permissions.as" ]